package io.wallet.service;

import io.wallet.entity.Wallet;
import io.wallet.entity.WalletResponse;
import io.wallet.entity.WalletStatus;
import io.wallet.exception.WalletNotFoundException;
import io.wallet.repository.WalletRepository;
import org.junit.jupiter.api.Test;

import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class WalletServiceTest {

    private final WalletRepository walletRepository =
        mock(WalletRepository.class);

    private final WalletService walletService =
        new WalletService(walletRepository);

    @Test
    void shouldReturnWalletResponse() {
        UUID walletId = UUID.randomUUID();

        Wallet wallet = new Wallet(
            15_000L,
            WalletStatus.ACTIVE
        );

        setWalletId(wallet, walletId);

        when(walletRepository.findById(walletId))
            .thenReturn(Optional.of(wallet));

        WalletResponse response =
            walletService.getWallet(walletId);

        assertEquals(walletId, response.id());
        assertEquals(15_000L, response.balancePaise());
        assertEquals("ACTIVE", response.status());

        verify(walletRepository)
            .findById(walletId);
    }

    @Test
    void shouldThrowWhenWalletDoesNotExist() {
        UUID walletId = UUID.randomUUID();

        when(walletRepository.findById(walletId))
            .thenReturn(Optional.empty());

        assertThrows(
            WalletNotFoundException.class,
            () -> walletService.getWallet(walletId)
        );

        verify(walletRepository)
            .findById(walletId);
    }

    /*
     * Wallet IDs are generated by @PrePersist.
     * Tests should not depend on manually invoking lifecycle
     * callbacks, so this helper assigns the generated ID through
     * persistence lifecycle simulation.
     */
    private void setWalletId(
        Wallet wallet,
        UUID expectedId
    ) {
        try {
            var field =
                Wallet.class.getDeclaredField("id");

            field.setAccessible(true);
            field.set(wallet, expectedId);

        } catch (ReflectiveOperationException exception) {
            throw new IllegalStateException(
                "Unable to prepare wallet test fixture",
                exception
            );
        }
    }
}
